run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - ineffassign
    - typecheck
    - varcheck
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - depguard
    - dupl
    - gocyclo
    - nakedret
    - unparam
    - whitespace

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line 