name: CI

on:
  push:
    branches: [ MAIN-001 ]
  pull_request:
    branches: [ MAIN-001 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2
      - name: Lint
        run: golangci-lint run
      - name: Build
        run: go build -v ./cmd/main.go
      - name: Test
        run: go test -v ./...
      - name: Coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out 