name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: '1.21'
  CGO_ENABLED: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build for multiple platforms
      env:
        CGO_ENABLED: 0
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w -X main.version=$VERSION" -o clisland-linux-amd64 ./cmd/main.go
        GOOS=linux GOARCH=arm64 go build -v -ldflags="-s -w -X main.version=$VERSION" -o clisland-linux-arm64 ./cmd/main.go
        GOOS=darwin GOARCH=amd64 go build -v -ldflags="-s -w -X main.version=$VERSION" -o clisland-darwin-amd64 ./cmd/main.go
        GOOS=darwin GOARCH=arm64 go build -v -ldflags="-s -w -X main.version=$VERSION" -o clisland-darwin-arm64 ./cmd/main.go
        GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w -X main.version=$VERSION" -o clisland-windows-amd64.exe ./cmd/main.go
        GOOS=windows GOARCH=arm64 go build -v -ldflags="-s -w -X main.version=$VERSION" -o clisland-windows-arm64.exe ./cmd/main.go

    - name: Create checksums
      run: |
        sha256sum clisland-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          clisland-*
          checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false 